[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_counter = "8sbbinVKBHTxWBd1oDrjUnHY9GqB2QJJq4YeUdPnnVM6"
cpi_signer = "FxhAgWhnKhghCtTF2c6fPxo1LKueHTuypjTR6fSejJXS"
escrow = "3VXioM77xHLhNycAN4pkpHAsp6hZyDxnSieKQd7Kyt8r"
pubkey_arg = "CszGbucGUE2H5gwuGZQNmAJ1Qe1uHmst36ZmxP4Z4yvy"
puppet = "5TBggU5sCesWSqkSc44xzKZwhM8FRT4KhTMXK1LoerJG"
puppet_master = "F4YurBauRjWpHpynNZhARWezDoDc2wLCWTjoihe338Ck"
reviews_variable_len = "3M8LR1Ss2m49AKCZnUUndUthtJGwHxiA1W25N8aJj3vf"
smart_wallet = "12ojTiLE1QzfpucQd9rfiibrhqTRXQ3jMbUnGN5BzA3a"
spl_demo = "6v1TvN4fWHEAbJmphQaAE28ihkgUPijiFyY6sHysvDU5"
token_2022 = "QJqxGatfoyyHgeuxNgur5EWETdXGzYx2hBkdtrbT2gZ"
virtual_xyk = "AxqJANBzF2LxPQDh33jVSRut8Tsnq5Ag5iDwVg7st9CN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
